import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./_components/header";
import Providers from "@/components/providers/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <Providers>
                <body className={inter.className}>
                    <Header />
                    {children}
                </body>
            </Providers>
        </html>
    );
}
